### ISSUE TITLE
Hello. Can you give all credits to ImagicalGamer? Thanks.

### ISSUE THREAD

**Issue by ghost** [Muqsit/mcMMO#1]
Hello. Can you give all credits to ImagicalGamer? Thanks.

**Comment by Muqsit** [comment]
Why should I credit someone for what I originally wrote? Every single word was written by me. There aren't any PRs made so far.

**Comment by ghost** [comment]
If you say that, ok. But i'm not sure 100% ;)

**Comment by ghost** [comment]
And you implement wood cutter, implement and auto-plant sappling ;)

**Comment by Muqsit** [comment]
Woodcutting is fully done, I am thinking of working on repair skill next because it's sort of easy. I'll add auto-planting to woodcutting in the next commit

**Comment by ghost** [comment]
Ok, good. Thanks.

**Comment by ghost** [comment]
@Muqsit Update coming?
